# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=nexo
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data